version: "3"

# # override the default network
# networks:
#   default:
#     external:
#       name: college-system-network

services:
  app:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
      args:
        VARIANT: 14-buster

    container_name: app
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    working_dir: /workspace/nodejs_app
    entrypoint: ["bash", "start.sh", "2124"]
    expose:
      - "2124"

  mysql_app:
    image: mysql
    container_name: mysql_db_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: college_system
    ports:
      - "3306:3306"

        # Run the caddy server
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"

    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
